### ISSUE TITLE
Can't get attribute 'FeatureLoss' on <module '__main__' (built-in)>

### ISSUE THREAD

**Issue by PaganMax** [lacti/artline#1]
Thank you very much for your resources. With be in Linux environment, Uwsgi deployment, error still occurs:

Traceback (most recent call last):
  File "/home/avatar_app/./wsgi.py", line 2, in <module>
    from arlineapp import app as application
  File "/home/avatar_app/./arlineapp.py", line 30, in <module>
    learn=load_learner(Path(path), 'ArtLine_650.pkl')
  File "/home/avatar_app/avatar_appenv/lib/python3.8/site-packages/fastai/basic_train.py", line 621, in load_learner
    state = torch.load(source, map_location='cpu') if defaults.device == torch.device('cpu') else torch.load(source)
  File "/home/avatar_app/avatar_appenv/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/avatar_app/avatar_appenv/lib/python3.8/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'FeatureLoss' on <module '__main__' (built-in)>
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 2739, cores: 1)

but, In the same situation, I can run my service in Python, so how can I fix it

**Comment by ez4lgd** [comment]
Same absolutely! QAQ
